orgs:
  rhoai-rhtap:
    admins:
    - dchourasia
    - MohammadiIram
    - riprasad
    default_repository_permission: read
    description: "Organization for RHOAI RHTAP Org"
    has_organization_projects: true
    has_repository_projects: true
    members:
    - aloganat
    - moulalis
    members_can_create_repositories: false
    name: rhoai-rhtap
    teams: {}
