name: Apply Organization Membership
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - "config/rhoai-rhtap/org.yaml"
permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.RHOAI_DEVOPS_APP_ID }}
          private_key: ${{ secrets.RHOAI_DEVOPS_APP_PRIVATE_KEY }}
  peribolos:
    needs: [ setup ]
    runs-on: ubuntu-latest
    container:
      image: gcr.io/k8s-prow/peribolos
    steps:
      - uses: actions/checkout@v3
      - name: Apply organization membership
        run: |
          echo ${{ secrets.RHOAI_GITHUB_TOKEN }} > /.github_token.txt
          peribolos --github-token-path /.github_token.txt --config-path "config/rhoai-rhtap/org.yaml" --fix-org --fix-org-members --confirm --min-admins=3
